spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SafeTalk
    username: hyeonmarina
    password: 0808
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

